// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSqfGq2OZsZwM9OSgkUYsoVuYltzzeOmc',
    appId: '1:396641823945:web:05c7937ec06791169a7118',
    messagingSenderId: '396641823945',
    projectId: 'triply-f9b82',
    authDomain: 'triply-f9b82.firebaseapp.com',
    storageBucket: 'triply-f9b82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRDcCwBfcOB9oCA1pi3lqoAcxl94SjEM',
    appId: '1:396641823945:android:a85fe3db728476489a7118',
    messagingSenderId: '396641823945',
    projectId: 'triply-f9b82',
    storageBucket: 'triply-f9b82.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzEqJh9R2qaLCpuBWIaGIG_7mT6rHzIF4',
    appId: '1:396641823945:ios:74a377c04134b1be9a7118',
    messagingSenderId: '396641823945',
    projectId: 'triply-f9b82',
    storageBucket: 'triply-f9b82.firebasestorage.app',
    androidClientId: '396641823945-8ocqjhhbk0mj82k9ds085dov653m3jcu.apps.googleusercontent.com',
    iosClientId: '396641823945-3um5pcg2ckh3bb482nfeib4tnres28uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.triply',
  );
}
